export const GET_ATTRACTION_INTRO = 'GET_ATTRACTION_INTRO'
export const GET_ATTRACTION_QUESTIONS = 'GET_ATTRACTION_QUESTIONS'
export const GET_ATTRACTION_QUESTION_ANSWER = 'GET_ATTRACTION_QUESTION_ANSWER'
