export const GET_ATTRACTIONS_BY_CITY = 'GET_ATTRACTIONS_BY_CITY'
export const GET_ATTRACTIONS_BY_COORDS = 'GET_ATTRACTIONS_BY_COORDS'
export const GET_ATTRACTION_INTRO = 'GET_ATTRACTION_INTRO'
export const GET_ATTRACTION_BY_NAME = 'GET_ATTRACTION_BY_NAME'
